[package]
name = "libp2p-relay-server"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"
description = "A limited relay server implementing the circuit relay v2 protocol."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.3"
futures = "0.3.15"
hex = "0.4.2"
libp2p = { git = "https://github.com/mxinden/rust-libp2p", branch = "metrics-and-relay-v2", default-features = false, features = ["dns-async-std", "noise", "tcp-async-io", "yamux", "identify", "kad", "ping", "relay", "metrics"] }
log = "0.4"
open-metrics-client = "0.9"
structopt = "0.3.21"
tide = "0.16"
