[package]
name = "libp2p-server"
version = "0.5.1"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"
description = "A rust-libp2p server binary."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
base64 = "0.13"
env_logger = "0.9.0"
futures = "0.3.18"
futures-timer = "3"
libp2p = { git = "https://github.com/mxinden/rust-libp2p", branch = "relay-v2", default-features = false, features = ["dns-async-std", "noise", "tcp-async-io", "yamux", "identify", "kad", "ping", "relay", "metrics"] }
log = "0.4"
open-metrics-client = "0.12.0"
serde = "1.0.130"
serde_derive = "1.0.125"
serde_json = "1.0"
structopt = "0.3.25"
tide = "0.16"
zeroize = "1"
